[mgr]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true # Matches your eza alias logic
show_hidden    = true

[preview]
tab_size        = 4
max_width       = 1000
max_height      = 1000
cache_dir       = ""
image_filter    = "triangle" # Better performance on older GPUs

[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Neovim" }
]
